<?php

namespace UrlShortenerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository {

    private $name = "url";

    public function countId() {
        return $this->createQueryBuilder($this->name)
                        ->select('COUNT(' . $this->name . ')')
                        ->getQuery()
                        ->getSingleScalarResult();
    }

}
